[tools]
lefthook = "2.0.16"
"cargo:ast-grep" = "0.40.4"

# lefthook hooks
actionlint = "1.7.10"
bun = "1.3.8"
"cargo:basefmt" = "0.1.0"
"npm:@commitlint/cli" = "20.4.0"
"npm:prettier" = "3.8.1"
shellcheck = "0.11.0"
shfmt = "3.12.0"

[settings]
npm.bun = true
